#!/usr/bin/env ruby
#^syntax detection

site "http://community.opscode.com/api/v1"

cookbook "apt"
cookbook "chef-server"
cookbook "git"
cookbook "ntp"
cookbook "openvpn"
cookbook "sudo"
cookbook "ubuntu"
cookbook "users"
cookbook "zsh"

cookbook "rithis-guests", :path => "my_cookbooks/rithis-guests"
